"""Factory for the MCP terminal server."""

from __future__ import annotations

import logging
import multiprocessing
import os
import signal
import sys
import weakref
from datetime import datetime
from multiprocessing import Process
from multiprocessing.queues import Queue as MultiprocessingQueue
from queue import Empty
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Any

import anyio
from anyio.abc import TaskGroup as AnyIOTaskGroup

from mcp.server.fastmcp import Context, FastMCP
from mcp.server.session import ServerSession

from .config import ServerConfig
from .files import FileEditor, FileOperationError, FileOperationResult
from .plugin import (
    FileOperationEvent,
    GlobalPluginManager,
    PluginManager,
    ServerWarningEvent,
)
from .shell import CommandExecutionError, CommandResult, CommandTimeoutError, ShellCommandExecutor
from .streaming import CommandCompleteEvent, utcnow


logger = logging.getLogger(__name__)


@dataclass(slots=True)
class ChatBridgeEnvelope:
    """Container for inter-process chat bridge messages."""

    kind: str
    payload: str | None = None


_ENVELOPE_KIND_MESSAGE = "message"
_ENVELOPE_KIND_STOP = "stop"
_ENVELOPE_KIND_SHUTDOWN = "shutdown"
_ENVELOPE_KIND_APPEND = "append"


@dataclass(slots=True)
class ApplicationState:
    """Objects shared across MCP requests."""

    config: ServerConfig
    plugin_manager: PluginManager
    executor: ShellCommandExecutor
    chat_bridge: "UserChatBridge"


class UserChatBridge:
    """Coordinate the optional PyQt5-based chat window for server-side messaging.

    The bridge spins up a PyQt5 user interface within a dedicated helper process
    whenever the environment provides a display server and the :mod:`PyQt5`
    package is available. Messages entered into the window propagate to all
    connected MCP sessions as informational log events prefixed with the
    mandatory alert text.

    The implementation purposely avoids monkey patching or simulation so the
    live server infrastructure remains untouched. Message dispatch occurs via
    ``ServerSession.send_log_message`` to ensure ordering with existing log
    streams and stdout/stderr output generated by running commands.
    """

    _MESSAGE_PREFIX = "[MESSAGE FROM USER. DO NOT IGNORE:]"
    _SENTINEL = object()

    def __init__(self, *, plugin_manager: PluginManager, console_echo: bool) -> None:
        self._plugin_manager = plugin_manager
        self._console_echo = console_echo
        self._message_queue: MultiprocessingQueue[ChatBridgeEnvelope] | None = None
        self._control_queue: MultiprocessingQueue[ChatBridgeEnvelope] | None = None
        self._sessions: weakref.WeakSet[ServerSession] = weakref.WeakSet()
        self._gui_process: Process | None = None
        self._task_group: AnyIOTaskGroup | None = None
        self._active = False
        self._pump_cancel_scope: anyio.CancelScope | None = None
        self._qt_available = False
        self._initialize_qt_support()

    def _initialize_qt_support(self) -> None:
        """Attempt to import PyQt5 and confirm a GUI display is available."""

        if sys.platform.startswith("linux") and not os.environ.get("DISPLAY"):
            logger.warning("User chat window disabled because DISPLAY is not set.")
            return
        try:  # pragma: no cover - GUI components are not exercised in tests
            from PyQt5 import QtCore, QtWidgets  # type: ignore
        except Exception as exc:  # pragma: no cover - optional dependency
            logger.warning("PyQt5 is unavailable; user chat window disabled: %s", exc)
            return

        self._qt_available = True

    @property
    def is_active(self) -> bool:
        """Return ``True`` when the chat bridge successfully started."""

        return self._active

    def register_context(self, ctx: Context[ServerSession, ApplicationState]) -> None:
        """Record the session associated with ``ctx`` for subsequent broadcasts."""

        if not self._active:
            return
        try:
            session = ctx.request_context.session
        except ValueError:
            return
        if session is None:
            return
        self._sessions.add(session)

    async def __aenter__(self) -> "UserChatBridge":
        """Start background tasks and GUI helper process when PyQt5 support is present."""

        if not self._qt_available:
            logger.info("User chat bridge inactive: PyQt5 support not detected.")
            self._plugin_manager.register_export("mcp2term.user_chat.bridge", self)
            return self

        self._message_queue = multiprocessing.Queue()
        self._control_queue = multiprocessing.Queue()
        self._task_group = await anyio.create_task_group().__aenter__()
        try:
            self._task_group.start_soon(self._message_pump)
            self._start_gui_process()
        except Exception:
            await self._shutdown_tasks()
            raise
        else:
            self._active = True
            self._plugin_manager.register_export("mcp2term.user_chat.bridge", self)
            logger.info("User chat bridge initialised with PyQt5 user interface.")
        return self

    async def __aexit__(self, exc_type, exc, exc_tb) -> None:
        """Shut down the GUI helper process and message pump."""

        await self._shutdown_tasks()

    async def _shutdown_tasks(self) -> None:
        """Terminate all background resources owned by the bridge."""

        if self._pump_cancel_scope is not None:
            self._pump_cancel_scope.cancel()
        if self._message_queue is not None:
            try:
                self._message_queue.put_nowait(ChatBridgeEnvelope(kind=_ENVELOPE_KIND_STOP))
            except Exception:  # pragma: no cover - defensive logging
                logger.exception("Failed to notify message pump about shutdown")
        if self._control_queue is not None:
            try:
                self._control_queue.put_nowait(ChatBridgeEnvelope(kind=_ENVELOPE_KIND_SHUTDOWN))
            except Exception:  # pragma: no cover - defensive logging
                logger.exception("Failed to notify PyQt process about shutdown")

        if self._task_group is not None:
            await self._task_group.__aexit__(None, None, None)
            self._task_group = None

        if self._gui_process is not None:
            self._gui_process.join(timeout=5)
            if self._gui_process.is_alive():
                self._gui_process.terminate()
                self._gui_process.join(timeout=2)
            self._gui_process = None

        self._plugin_manager.register_export("mcp2term.user_chat.bridge", None)
        self._active = False
        if self._message_queue is not None:
            self._message_queue.close()
            self._message_queue.join_thread()
        if self._control_queue is not None:
            self._control_queue.close()
            self._control_queue.join_thread()
        self._message_queue = None
        self._control_queue = None
        self._sessions = weakref.WeakSet()
        self._pump_cancel_scope = None

    def _start_gui_process(self) -> None:
        """Launch the PyQt5 UI loop inside a dedicated helper process."""

        if not self._qt_available:
            return
        if self._message_queue is None or self._control_queue is None:
            raise RuntimeError("Chat bridge queues must be initialised before starting the GUI process")
        if self._gui_process is not None and self._gui_process.is_alive():
            return

        self._gui_process = Process(
            target=_run_pyqt_bridge_process,
            name="mcp2term-user-chat-ui",
            daemon=True,
            args=(self._message_queue, self._control_queue),
        )
        self._gui_process.start()

    async def _message_pump(self) -> None:
        """Continuously deliver user messages to all tracked sessions."""

        queue = self._message_queue
        if queue is None:
            logger.debug("Message pump aborted because queues are uninitialised.")
            return

        with anyio.CancelScope() as scope:
            self._pump_cancel_scope = scope
            while True:
                try:
                    envelope = await anyio.to_thread.run_sync(queue.get)
                except (EOFError, OSError):  # pragma: no cover - unexpected transport failure
                    logger.warning("Chat bridge queue closed unexpectedly; stopping message pump")
                    break
                if not isinstance(envelope, ChatBridgeEnvelope):
                    logger.debug("Ignoring unexpected payload from chat bridge: %r", envelope)
                    continue
                if envelope.kind == _ENVELOPE_KIND_STOP:
                    break
                if envelope.kind == _ENVELOPE_KIND_MESSAGE and envelope.payload:
                    await self._broadcast_message(envelope.payload)
        self._pump_cancel_scope = None

    async def _broadcast_message(self, message: str) -> None:
        """Send ``message`` to every connected session as a log entry."""

        formatted = f"{self._MESSAGE_PREFIX} {message}"
        active_sessions = [session for session in list(self._sessions) if session is not None]
        failures = 0
        for session in active_sessions:
            try:
                await session.send_log_message("info", formatted, logger="user-chat")
            except Exception:  # pragma: no cover - network/runtime variability
                failures += 1
                logger.exception("Failed to deliver user chat message to a session")
                self._sessions.discard(session)
        logger.info(
            "User chat message dispatched to %d sessions (%d failures): %s",
            len(active_sessions),
            failures,
            message,
        )
        if self._console_echo:
            print(formatted, flush=True)


def _run_pyqt_bridge_process(
    message_queue: MultiprocessingQueue[ChatBridgeEnvelope],
    control_queue: MultiprocessingQueue[ChatBridgeEnvelope],
) -> None:  # pragma: no cover - requires PyQt5 GUI environment
    """Entry point executed in a helper process to host the PyQt5 chat window."""

    try:
        from PyQt5 import QtCore, QtGui, QtWidgets  # type: ignore
    except Exception:  # pragma: no cover - defensive import logging
        logging.exception("Unable to import PyQt5; user chat window will not start")
        return

    app = QtWidgets.QApplication.instance()
    created_app = False
    if app is None:
        app = QtWidgets.QApplication(["mcp2term-user-chat"])
        created_app = True

    class ChatWindow(QtWidgets.QMainWindow):
        """Interactive window emitting chat messages to the parent process."""

        def __init__(self) -> None:
            super().__init__()
            self.setWindowTitle("mcp2term User Message Bridge")
            self.setMinimumWidth(480)
            self.setMinimumHeight(320)
            self._build_interface()

        def _build_interface(self) -> None:
            container = QtWidgets.QWidget(self)
            layout = QtWidgets.QVBoxLayout(container)

            headline = QtWidgets.QLabel(
                (
                    "Enter a message to broadcast immediately to all connected "
                    "MCP clients. Messages are delivered as informational log "
                    "entries and appear inline with command output."
                ),
                self,
            )
            headline.setWordWrap(True)
            layout.addWidget(headline)

            self._history = QtWidgets.QTextEdit(self)
            self._history.setReadOnly(True)
            self._history.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
            self._history.setPlaceholderText("No messages have been sent yet.")
            layout.addWidget(self._history)

            input_row = QtWidgets.QHBoxLayout()
            self._input = QtWidgets.QLineEdit(self)
            self._input.setPlaceholderText("Type the message to send to clients...")
            input_row.addWidget(self._input)

            send_button = QtWidgets.QPushButton("Send", self)
            input_row.addWidget(send_button)
            layout.addLayout(input_row)

            container.setLayout(layout)
            self.setCentralWidget(container)

            send_button.clicked.connect(self._on_send_clicked)  # type: ignore[arg-type]
            self._input.returnPressed.connect(self._on_send_clicked)  # type: ignore[arg-type]

        def _append_history(self, text: str) -> None:
            timestamp = datetime.now().strftime("%H:%M:%S")
            self._history.append(f"{timestamp}  {text}")

        def _on_send_clicked(self) -> None:
            text = self._input.text().strip()
            if not text:
                return
            self._input.clear()
            self._append_history(f"You: {text}")
            message_queue.put(ChatBridgeEnvelope(kind=_ENVELOPE_KIND_MESSAGE, payload=text))

        def closeEvent(self, event: "QtGui.QCloseEvent") -> None:  # type: ignore[name-defined]
            event.ignore()
            self.hide()

    window = ChatWindow()
    window.show()

    def _drain_control_queue() -> None:
        while True:
            try:
                envelope = control_queue.get_nowait()
            except Empty:
                break
            except (EOFError, OSError):  # pragma: no cover - parent process terminated
                app.quit()
                return
            if isinstance(envelope, ChatBridgeEnvelope):
                if envelope.kind == _ENVELOPE_KIND_SHUTDOWN:
                    app.quit()
                elif envelope.kind == _ENVELOPE_KIND_APPEND and envelope.payload:
                    window._append_history(envelope.payload)
            else:  # pragma: no cover - defensive logging
                logging.getLogger(__name__).debug(
                    "Ignoring unexpected control payload in PyQt process: %r", envelope
                )

    poll_timer = QtCore.QTimer()
    poll_timer.setInterval(100)
    poll_timer.timeout.connect(_drain_control_queue)  # type: ignore[arg-type]
    poll_timer.start()

    app.exec_()

    try:
        message_queue.put(ChatBridgeEnvelope(kind=_ENVELOPE_KIND_STOP))
    except Exception:  # pragma: no cover - queue already closed
        logging.getLogger(__name__).debug("Unable to notify parent about PyQt shutdown")

    if created_app:
        app.quit()


def _serialize_result(result: CommandResult, *, timed_out: bool) -> dict[str, Any]:
    return {
        "command_id": result.request.command_id,
        "command": result.request.command,
        "working_directory": result.request.working_directory,
        "return_code": result.return_code,
        "stdout": result.stdout,
        "stderr": result.stderr,
        "started_at": result.started_at.isoformat(),
        "finished_at": result.finished_at.isoformat(),
        "duration": result.duration,
        "timed_out": timed_out,
        "pty_allocated": result.pty_allocated,
    }


def _serialize_timeout(event: CommandTimeoutError) -> dict[str, Any]:
    assert event.event is not None
    return {
        "command_id": event.event.request.command_id,
        "command": event.event.request.command,
        "working_directory": event.event.request.working_directory,
        "return_code": event.event.return_code,
        "stdout": event.event.stdout,
        "stderr": event.event.stderr,
        "started_at": event.event.started_at.isoformat(),
        "finished_at": event.event.finished_at.isoformat(),
        "duration": event.event.duration,
        "timed_out": True,
        "pty_allocated": event.event.request.allocate_pty,
    }


def _serialize_event(event: CommandCompleteEvent, *, timed_out: bool) -> dict[str, Any]:
    result = CommandResult(
        request=event.request,
        stdout=event.stdout,
        stderr=event.stderr,
        return_code=event.return_code,
        started_at=event.started_at,
        finished_at=event.finished_at,
        pty_allocated=event.request.allocate_pty,
    )
    return _serialize_result(result, timed_out=timed_out)


def _resolve_signal(value: str | int | None) -> int:
    if value is None:
        return signal.SIGINT
    if isinstance(value, int):
        return value
    normalized = value.upper()
    if not normalized.startswith("SIG"):
        normalized = f"SIG{normalized}"
    try:
        return getattr(signal, normalized)
    except AttributeError as exc:  # pragma: no cover - defensive branch
        raise ValueError(f"Unknown signal: {value}") from exc


async def _emit_server_warning(
    ctx: Context[ServerSession, ApplicationState],
    state: ApplicationState,
    *,
    tool_name: str,
    base_message: str,
    exception: BaseException | None = None,
    details: dict[str, Any] | None = None,
) -> str:
    details = details or {}
    if exception is not None and base_message:
        message = f"{base_message}: {exception}"
    elif exception is not None:
        message = str(exception)
    else:
        message = base_message

    logger.warning("%s warning: %s", tool_name, message, exc_info=exception)
    try:
        await ctx.warning(message)
    except Exception:  # pragma: no cover - defensive logging
        logger.exception("Failed to deliver warning to client for %s", tool_name)

    await state.plugin_manager.emit_server_warning(
        ServerWarningEvent(
            tool_name=tool_name,
            message=message,
            details=details,
            exception=exception,
        )
    )
    return message


def _append_warning(payload: dict[str, Any], warning: str) -> dict[str, Any]:
    existing = payload.get("warnings")
    if isinstance(existing, (list, tuple, set)):
        warnings = [str(item) for item in existing if item]
    elif existing:
        warnings = [str(existing)]
    else:
        warnings = []
    warnings.append(warning)
    payload["warnings"] = warnings
    return payload


def _basic_command_failure(
    command: str,
    working_directory: Path | None,
    command_id: str | None,
    message: str,
) -> dict[str, Any]:
    finished = utcnow()
    cwd = str(working_directory) if working_directory is not None else ""
    return {
        "command_id": command_id or "",
        "command": command,
        "working_directory": cwd,
        "return_code": -1,
        "stdout": "",
        "stderr": message,
        "started_at": finished.isoformat(),
        "finished_at": finished.isoformat(),
        "duration": 0.0,
        "timed_out": False,
        "pty_allocated": False,
    }


def create_server(
    *,
    config: ServerConfig | None = None,
    plugin_manager: PluginManager | None = None,
) -> FastMCP:
    """Create a configured FastMCP server instance."""

    resolved_config = config or ServerConfig.from_env()
    manager = plugin_manager or GlobalPluginManager
    manager.refresh_exports()
    manager.set_console_echo_enabled(resolved_config.console_echo)

    @asynccontextmanager
    async def lifespan(_: FastMCP) -> AsyncIterator[ApplicationState]:
        await manager.load_plugins_async(resolved_config.plugin_modules)
        executor = ShellCommandExecutor(resolved_config, manager)
        chat_bridge = UserChatBridge(
            plugin_manager=manager,
            console_echo=resolved_config.console_echo,
        )
        async with chat_bridge:
            state = ApplicationState(
                config=resolved_config,
                plugin_manager=manager,
                executor=executor,
                chat_bridge=chat_bridge,
            )
            try:
                yield state
            finally:
                pass

    server = FastMCP(
        name="mcp2term",
        instructions=(
            "Execute shell commands with streaming output for stdout and stderr. "
            "Use responsibly and prefer safe commands."
        ),
        lifespan=lifespan,
    )

    @server.tool(name="run_command", description="Execute a shell command with live stdout/stderr streaming.")
    async def run_command(  # type: ignore[no-redef]
        command: str,
        *,
        working_directory: str | None = None,
        environment: dict[str, str] | None = None,
        timeout: float | None = None,
        command_id: str | None = None,
        allocate_pty: bool | None = None,
        ctx: Context[ServerSession, ApplicationState],
    ) -> dict[str, Any]:
        target_path = Path(working_directory).expanduser().resolve() if working_directory else None
        state = ctx.request_context.lifespan_context
        state.chat_bridge.register_context(ctx)
        details = {
            "command": command,
            "command_id": command_id or "",
            "working_directory": str(target_path) if target_path else "",
            "allocate_pty": bool(allocate_pty),
        }
        try:
            result = await ctx.request_context.lifespan_context.executor.run(
                command,
                ctx=ctx,
                working_directory=target_path,
                environment=environment,
                timeout=timeout,
                command_id=command_id,
                allocate_pty=bool(allocate_pty),
            )
            return _serialize_result(result, timed_out=False)
        except CommandTimeoutError as exc:
            if exc.event is None:
                warning = await _emit_server_warning(
                    ctx,
                    state,
                    tool_name="run_command",
                    base_message=f"Command '{command}' timed out",
                    exception=exc,
                    details=details,
                )
                return _append_warning(
                    _basic_command_failure(command, target_path, command_id, str(exc)),
                    warning,
                )
            warning = await _emit_server_warning(
                ctx,
                state,
                tool_name="run_command",
                base_message=f"Command '{command}' timed out",
                exception=exc,
                details=details,
            )
            return _append_warning(_serialize_timeout(exc), warning)
        except CommandExecutionError as exc:
            warning = await _emit_server_warning(
                ctx,
                state,
                tool_name="run_command",
                base_message="Command execution failed",
                exception=exc,
                details=details,
            )
            if exc.event is not None:
                return _append_warning(_serialize_event(exc.event, timed_out=False), warning)
            return _append_warning(
                _basic_command_failure(command, target_path, command_id, str(exc)),
                warning,
            )
        except Exception as exc:
            warning = await _emit_server_warning(
                ctx,
                state,
                tool_name="run_command",
                base_message="Unexpected error while executing command",
                exception=exc,
                details=details,
            )
            return _append_warning(
                _basic_command_failure(command, target_path, command_id, str(exc)),
                warning,
            )

    @server.tool(name="cancel_command", description="Send a signal to a running command.")
    async def cancel_command(  # type: ignore[no-redef]
        command_id: str,
        *,
        signal_value: str | int | None = None,
        ctx: Context[ServerSession, ApplicationState],
    ) -> dict[str, Any]:
        state = ctx.request_context.lifespan_context
        state.chat_bridge.register_context(ctx)
        details = {"command_id": command_id, "signal_value": signal_value}
        try:
            resolved_signal = _resolve_signal(signal_value)
        except ValueError as exc:
            warning = await _emit_server_warning(
                ctx,
                state,
                tool_name="cancel_command",
                base_message="Invalid signal value",
                exception=exc,
                details=details,
            )
            return {
                "command_id": command_id,
                "signal": None,
                "signal_name": None,
                "delivered": False,
                "warnings": [warning],
            }

        try:
            delivered = await ctx.request_context.lifespan_context.executor.send_signal(
                command_id,
                resolved_signal,
            )
            try:
                signal_name = signal.Signals(resolved_signal).name
            except ValueError:  # pragma: no cover - non-standard signal
                signal_name = str(resolved_signal)
            response = {
                "command_id": command_id,
                "signal": resolved_signal,
                "signal_name": signal_name,
                "delivered": delivered,
            }
        except Exception as exc:
            warning = await _emit_server_warning(
                ctx,
                state,
                tool_name="cancel_command",
                base_message="Failed to send signal to command",
                exception=exc,
                details=details,
            )
            response = {
                "command_id": command_id,
                "signal": resolved_signal,
                "signal_name": None,
                "delivered": False,
                "warnings": [warning],
            }
        else:
            if not delivered:
                warning = await _emit_server_warning(
                    ctx,
                    state,
                    tool_name="cancel_command",
                    base_message=f"No running command matches {command_id}; signal not delivered",
                    exception=None,
                    details=details,
                )
                response = _append_warning(response, warning)
        return response

    @server.tool(name="send_stdin", description="Forward input to a running command's stdin pipe.")
    async def send_stdin(  # type: ignore[no-redef]
        command_id: str,
        data: str | None = None,
        *,
        eof: bool = False,
        ctx: Context[ServerSession, ApplicationState],
    ) -> dict[str, Any]:
        payload = data or ""
        state = ctx.request_context.lifespan_context
        state.chat_bridge.register_context(ctx)
        details = {"command_id": command_id, "data_length": len(payload), "eof": eof}
        try:
            accepted = await state.executor.send_stdin(
                command_id,
                payload,
                eof=eof,
            )
        except Exception as exc:
            warning = await _emit_server_warning(
                ctx,
                state,
                tool_name="send_stdin",
                base_message="Failed to forward stdin to command",
                exception=exc,
                details=details,
            )
            return {
                "command_id": command_id,
                "accepted": False,
                "eof": eof,
                "warnings": [warning],
            }
        response = {
            "command_id": command_id,
            "accepted": accepted,
            "eof": eof,
        }
        if not accepted:
            warning = await _emit_server_warning(
                ctx,
                state,
                tool_name="send_stdin",
                base_message="Command is not accepting additional stdin",
                exception=None,
                details=details,
            )
            response = _append_warning(response, warning)
        return response

    @server.tool(
        name="manage_file",
        description=(
            "Create, edit, and inspect files on the remote host including line-based operations."
        ),
    )
    async def manage_file(  # type: ignore[no-redef]
        path: str,
        *,
        operation: str,
        content: str | None = None,
        line: int | None = None,
        start_line: int | None = None,
        end_line: int | None = None,
        encoding: str = "utf-8",
        create_parents: bool = False,
        overwrite: bool = False,
        create_if_missing: bool = True,
        ctx: Context[ServerSession, ApplicationState],
    ) -> dict[str, Any]:
        state = ctx.request_context.lifespan_context
        state.chat_bridge.register_context(ctx)
        editor = FileEditor(state.config.working_directory)
        resolved_path = editor.resolve_path(path)

        request_arguments: dict[str, Any] = {
            "path": path,
            "encoding": encoding,
            "create_parents": create_parents,
            "overwrite": overwrite,
            "create_if_missing": create_if_missing,
            "resolved_path": str(resolved_path),
        }
        if content is not None:
            request_arguments["content"] = content
        if line is not None:
            request_arguments["line"] = line
        if start_line is not None:
            request_arguments["start_line"] = start_line
        if end_line is not None:
            request_arguments["end_line"] = end_line

        def _failure(message: str) -> FileOperationResult:
            return FileOperationResult(
                path=resolved_path,
                operation=operation,
                success=False,
                changed=False,
                encoding=encoding,
                message=message,
            )

        async def _notify_plugins(
            result: FileOperationResult,
            *,
            warning: str | None = None,
        ) -> None:
            await state.plugin_manager.emit_file_operation(
                FileOperationEvent(
                    raw_path=path,
                    operation=operation,
                    arguments=MappingProxyType(dict(request_arguments)),
                    result=result,
                    warning=warning,
                )
            )

        try:
            match operation:
                case "create":
                    result = editor.create_file(
                        path,
                        text=content,
                        overwrite=overwrite,
                        create_parents=create_parents,
                        encoding=encoding,
                    )
                case "write":
                    result = editor.write_file(
                        path,
                        text=content or "",
                        create_parents=create_parents,
                        encoding=encoding,
                    )
                case "append":
                    if content is None:
                        raise FileOperationError("Append operation requires content text")
                    result = editor.append_text(
                        path,
                        text=content,
                        encoding=encoding,
                        create_if_missing=create_if_missing,
                    )
                case "insert":
                    if line is None:
                        raise FileOperationError("Insert operation requires a line number")
                    if content is None:
                        raise FileOperationError("Insert operation requires content text")
                    result = editor.insert_lines(
                        path,
                        line=line,
                        text=content,
                        encoding=encoding,
                    )
                case "replace":
                    if start_line is None:
                        raise FileOperationError("Replace operation requires start_line")
                    effective_end = end_line or start_line
                    result = editor.replace_range(
                        path,
                        start_line=start_line,
                        end_line=effective_end,
                        text=content or "",
                        encoding=encoding,
                    )
                case "delete":
                    if start_line is None:
                        raise FileOperationError("Delete operation requires start_line")
                    effective_end = end_line or start_line
                    result = editor.delete_range(
                        path,
                        start_line=start_line,
                        end_line=effective_end,
                        encoding=encoding,
                    )
                case "print":
                    result = editor.read_lines(
                        path,
                        start_line=start_line,
                        end_line=end_line,
                        encoding=encoding,
                    )
                case "locate":
                    if content is None:
                        raise FileOperationError("Locate operation requires content text")
                    result = editor.find_line_numbers(
                        path,
                        text=content,
                        encoding=encoding,
                    )
                case "patch":
                    if content is None:
                        raise FileOperationError("Patch operation requires diff content")
                    result = editor.apply_patch(
                        path,
                        patch_text=content,
                        encoding=encoding,
                    )
                case _:
                    raise FileOperationError(f"Unsupported file operation: {operation}")
        except FileOperationError as exc:
            warning = await _emit_server_warning(
                ctx,
                state,
                tool_name="manage_file",
                base_message=str(exc),
                exception=None,
                details={
                    "path": str(resolved_path),
                    "operation": operation,
                },
            )
            failure = _failure(str(exc))
            await _notify_plugins(failure, warning=warning)
            return _append_warning(failure.to_payload(), warning)
        except Exception as exc:  # pragma: no cover - defensive
            warning = await _emit_server_warning(
                ctx,
                state,
                tool_name="manage_file",
                base_message="Unexpected failure during file operation",
                exception=exc,
                details={
                    "path": str(resolved_path),
                    "operation": operation,
                },
            )
            failure = _failure(warning)
            await _notify_plugins(failure, warning=warning)
            return _append_warning(failure.to_payload(), warning)

        await _notify_plugins(result)
        return result.to_payload()

    return server
